### PR TITLE
Rponton/release 3 6 4

### PR DESCRIPTION
**Pull request by RiPont**

### CODE REVIEW

**Comment by jeffrymorris** [comment]
@RiPont -

You need to remote update and then rebase over release/3.6 branch, fixing in merge issues, before you create your commit and push it. It is probably be easier to ditch this PR and create a new one. I am not sure what the temp/3.6 branch is, maybe @RichardSmedley can fill us in?

-Jeff

**Review by jeffrymorris — CHANGES_REQUESTED** [review]
Read my comments RE: update/rebasing

**Comment by RichardSmedley** [comment]
Closing this, in favour of https://github.com/couchbase/docs-sdk-dotnet/commit/73aac6cbdacd32d62657d2620f9a43e8f84fc6d4

**Comment by RichardSmedley** [comment]
(the `temp` branches will persist until I - or someone else - gets time freed up to build proper release branches with the new Information Architecture that you can see in the Scala 1.7 and C++ 1.0 docs.)

**Pull request closed without merging**
