### PR TITLE
NCBC-2302: Getting started tidy up

### PR DESCRIPTION
**Pull request by ingenthr**
Updated the getting started to reflect most idomatic
API and correct some of the current state.

### CODE REVIEW

**Comment by ingenthr** [comment]
@brantburnett if you have a moment to have a look here, I'd appreciate it!

**Review by RichardSmedley — APPROVED** [review]
:+1:

**Comment by brantburnett** [comment]
@ingenthr Looks great to me, tried it on my machine. I just had to do the following steps to run locally, which I think is mostly by design:

1. Change the username/password for the cluster to match
2. Change from "bucket-name" to the name of a bucket that exists in my cluster
3. I ran in full VS instead of VSCode, and for some reason I had to do a command-line `dotnet restore` to get it to compile. I'm really not sure why, VS should have done the restore automatically.

I've also filed this issue, after which we can remove the extra PackageReference from the csproj: https://issues.couchbase.com/browse/NCBC-2460

**Comment by ingenthr** [comment]
Sounds good, thanks @brantburnett!

**Pull request merged**
