### PR TITLE
Release notes for Couchbase .NET SDK 3.4.4

### PR DESCRIPTION
**Pull request by jeffrymorris**

### CODE REVIEW

**Comment by jeffrymorris** [comment]
@RichardSmedley - can this be merged or should I ping someone else?

Thanks,
Jeff

**Comment by RichardSmedley** [comment]
> @RichardSmedley - can this be merged or should I ping someone else?
> 
> Thanks, Jeff

You pushed it at a weekend, without pinging me on Slack (or adding me as a reviewer) - and I've been task-focussed all week, ignoring my e-mail backlog ;)

Will look at it now  :+1:

**Review by RichardSmedley — APPROVED** [review]
Thanks @jeffrymorris 
Will merge this now, but please check the changes that I have made, to ensure that the wording matches the intent of the fixes.

**Comment by jeffrymorris** [comment]
@jeffrymorris 

Thanks! I don't have rights to assign you as a reviewer for some reason.

Jeff

**Comment by RichardSmedley** [comment]
> Thanks! I don't have rights to assign you as a reviewer for some reason.
> 
> Jeff

Ah - looks like you'll need @ingenthr or @brett19 to add you to https://github.com/orgs/couchbase/teams/sdk-maintainers/members - then you should be able to :+1:

**Comment by ingenthr** [comment]
Added you @jeffrymorris.

**Pull request merged**
